import { Cryptocurrency } from "../interfaces/Cryptocurrency";

export const data: Cryptocurrency[] = [
    {
      id: 'BCT',
      symbol: 'BCT',
      name: 'Bitcoin',
      price: '1,224.3',
      percentage: '1,45',
      increased: false,
      imageUrl: require('../assets/Bitcoin.png'),
    },
    {
      id: 'ETH',
      symbol: 'ETH',
      name: 'Ethereum',
      price: '123,224.3',
      percentage: '1,45',
      increased: true,
      imageUrl: require('../assets/Ethereum.png'),
    },
    {
      id: 'XRP',
      symbol: 'XRP',
      name: 'XRP',
      price: '1,224.3',
      percentage: '1,45',
      increased: false,
      imageUrl: require('../assets/XRP.png'),
    },
    {
      id: 'DOP',
      symbol: 'DOP',
      name: 'Polkadot',
      price: '1,224.3',
      percentage: '1,45',
      increased: true,
      imageUrl: require('../assets/Polkadot.png'),
    },
    {
      id: 'LTC',
      symbol: 'LTC',
      name: 'Litecoin',
      price: '1,224.3',
      percentage: '1,45',
      increased: false,
      imageUrl: require('../assets/Litecoin.png'),
    },
    {
      id: 'DDD',
      symbol: 'DDD',
      name: 'DDD',
      price: '1,224.3',
      percentage: '1,45',
      increased: true,
      imageUrl: require('../assets/Polkadot.png'),
    },
    {
      id: 'LLL',
      symbol: 'LLL',
      name: 'LLL',
      price: '1,224.3',
      percentage: '1,45',
      increased: false,
      imageUrl: require('../assets/Litecoin.png'),
    },
    {
      id: 'BBB',
      symbol: 'BBB',
      name: 'BBB',
      price: '1,224.3',
      percentage: '1,45',
      increased: true,
      imageUrl: require('../assets/Polkadot.png'),
    },
  ];

  